name: Nuget Publisher

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  build:
  
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
        source-url: https://nuget.pkg.github.com/${{github.repository_owner}}/index.json
      env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_AUTH_TOKEN}}       
    - name: dotnet restore
      run: dotnet restore 
    - name: dotnet build
      run: dotnet build -c Release --no-restore
    - name: dotnet pack
      run: dotnet pack -c Release -o packages
    - name: dotnet nuget push v2
      run: dotnet nuget push **/*.nupkg --source --skip-duplicate
    - name: dotnet nuget push v3
      run: dotnet nuget push ./KFramework/packages/*.nupkg --source --skip-duplicate
    - name: dotnet nuget push v4
      run: dotnet nuget push ./KFramework/KFramework/packages/*.nupkg --source --skip-duplicate
    - name: dotnet nuget push v5
      run: dotnet nuget push "**/*.nupkg" --source --skip-duplicate
    - name: dotnet nuget push v6
      run: dotnet nuget push "./KFramework/packages/*.nupkg" --source --skip-duplicate
    - name: dotnet nuget push v7
      run: dotnet nuget push "./KFramework/KFramework/packages/*.nupkg" --source --skip-duplicate
    - name: dotnet nuget push
      run: dotnet nuget push "./KFramework/packages/*.nupkg" --skip-duplicate
